name: Build.$(Date:yyyy-MM-dd).$(Rev:r)

trigger:
  batch: true
  branches:
    include:
      - master

pr: none

variables:
  - template: variables.yml

jobs:
  - job: WindowsBuild
    displayName: Windows Build
    strategy:
      matrix:
        X64Debug:
          BuildConfiguration: Debug
          BuildPlatform: x64
        X64Release:
          BuildConfiguration: Release
          BuildPlatform: x64
        X86Debug:
          BuildConfiguration: Debug
          BuildPlatform: x86
        X86Release:
          BuildConfiguration: Release
          BuildPlatform: x86
    pool:
      vmImage: 'windows-2019'
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 2
    steps:
      - checkout: self
        clean: false
        submodules: false

      - template: templates/windows-build.yml

      - template: templates/windows-publish.yml
