name: Build.$(Date:yyyy-MM-dd).$(Rev:r)

trigger:
  batch: true
  branches:
    include:
      - master

pr:
  - master

variables:
  runCodesignValidationInjection: false
  system.debug: true

jobs:
  - job: WindowsBuild
    displayName: Windows Build
    strategy:
      matrix:
        X64Debug:
          Flavor: Debug
          Architecture: x64
        X64Release:
          Flavor: Release
          Architecture: x64
        X86Debug:
          Flavor: Debug
          Architecture: x86
        X86Release:
          Flavor: Release
          Architecture: x86
    pool:
      vmImage: 'windows-2019'
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 2
    steps:
      - checkout: self
        clean: false
        submodules: false

      - template: templates/windows-build.yml
        parameters:
          Flavor: $(Flavor)
          Architecture: $(Architecture)

      - template: templates/windows-publish.yml
        parameters:
          Flavor: ${{ variables.Flavor }}
          Architecture: ${{ variables.Architecture }}
