name: Build.$(Date:yyyy-MM-dd).$(Rev:r)

trigger:
  batch: true
  branches:
    include:
      - master

pr:
  - master

variables:
  runCodesignValidationInjection: false
  system.debug: true

jobs:
  - job: WindowsBuild
    displayName: Windows Build
    strategy:
      matrix:
        X64Debug:
          BFlavor: Debug
          BArchitecture: x64
        X64Release:
          BFlavor: Release
          BArchitecture: x64
        X86Debug:
          BFlavor: Debug
          BArchitecture: x86
        X86Release:
          BFlavor: Release
          BArchitecture: x86
    pool:
      vmImage: 'windows-2019'
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 2
    steps:
      - checkout: self
        clean: false
        submodules: false

      - template: templates/windows-build.yml
        parameters:
          Flavor: $(BFlavor)
          Architecture: $(BArchitecture)

      - template: templates/windows-publish.yml
        parameters:
          Flavor: $(BFlavor)
          Architecture: $[ variables.BArchitecture ]
