name: pr.windows.$(Date:yyyy-MM-dd).rev$(Rev:r)

trigger: none
pr:
  - master

variables:
  WinSDK: 10.0.18362.0

jobs:
  - job: WindowsPR
    displayName: Windows PR
    strategy:
      matrix:
        X64Debug:
          Flavor: Debug
          Platform: x64
        # X64Release:
        #   Flavor: Release
        #   Platform: x64
        # X86Debug:
        #   Flavor: Debug
        #   Platform: x86
        # X86Release:
        #   Flavor: Release
        #   Platform: x86
    pool:
      vmImage: 'windows-2019'
    timeoutInMinutes: 30
    cancelTimeoutInMinutes: 2
    steps:
      - checkout: self
        clean: false
        submodules: false

      - script: choco install ninja
        displayName: Install Ninja

      - task: BatchScript@1
        displayName: Setup Visual C++ Environment
        inputs:
          filename: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
          arguments: '$(Platform) $(WinSDK)'
          modifyEnvironment: true

      - task: CMake@1
        displayName: Generate Ninja Build
        inputs:
          workingDirectory: $(Build.BinariesDirectory)
          cmakeArgs: -G Ninja -DCMAKE_TOOLCHAIN_FILE=$(Build.SourcesDirectory)\.ado\toolchain.windows.cmake $(Build.SourcesDirectory)

      - task: CmdLine@2
        displayName: Build
        inputs:
          workingDirectory: $(Build.BinariesDirectory)
          script: ninja -v
#
# TODO: add a unit-test task here -- CTest or googletesT
#
